id: P000444
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN6721
  title: སློབ་གཞི་འགྲེལ་བརྗོད་ངོ་མཚར་འཕྲུལ་གྱི་ལྡེ་མིག ༼ལོ་རིམ་དྲུག་པའི་དེབ་སྟོད་ཆ།༽
  author: ''
  volumes:
    e9895a8bde7b4ddebffdcd2eddfea003:
      image_group_id: I3CN6723
      title: Volume 1 of slob gzhi 'grel brjod ngo mtshar 'phrul gyi lde mig(lo rim
        drug pa'i deb stod cha/)
      volume_number: 1
      total_pages: 260
      base_file: v001.txt
